spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
      format_sql: true
      show-sql: true
      
  profiles:
    active: local

logging:
  level:
    org:
      springframework: info
      dallili: debug

jwt:
  secret: ${JWT_SECRET_KEY}

openai:
  organization: 
    id: ${OPENAI_ORGANIZATION_ID}
  project: 
    id: ${OPENAI_PROJECT_ID}
  api: 
    key: ${OPENAI_API_KEY}
    url: ${OPENAI_API_URL}
  model: ${OPENAI_MODEL}
